 /********************************************************************************
 * Copyright (c) 2025-2026 ZF Friedrichshafen AG
 *
 * This program and the accompanying materials are made available under the 
 * terms of the Apache License Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-License-Identifier: Apache-2.0 
 ********************************************************************************/

/**
@file signal_identifier.h
@date 2025-09-06 15:15:34
This file is the signal identifier header.
This file was generated by the DBC utility from:
  datalink_2doors_example.dbc
  DBC file version: 1.0.0.1
*/
#ifndef __DBC_GENERATED__SIGNALIDENTIFIER_H__20250906_151534_698__
#define __DBC_GENERATED__SIGNALIDENTIFIER_H__20250906_151534_698__

namespace Doors2ExampleFMU
{
   // Data Dispatch Service  signal names  to  dbc variable names                C-type   RX/TX  vss name space
    static std::string      dsDoor01LeftIsOpen  = "CAN_Input_L1.Door01LeftIsOpen";
    static std::string      dsDoor01RightIsOpen = "CAN_Input_R1.Door01RightIsOpen";
    static std::string      dsLockDoor01Left    = "CAN_Output.LockDoor01Left";	
    static std::string      dsLockDoor01Right   = "CAN_Output.LockDoor01Right";

} // Doors2ExampleFMU

#endif // __DBC_GENERATED__SIGNALIDENTIFIER_H__20250906_151534_698__
