 /********************************************************************************
 * Copyright (c) 2025-2026 ZF Friedrichshafen AG
 *
 * This program and the accompanying materials are made available under the 
 * terms of the Apache License Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-License-Identifier: Apache-2.0 
 *
 * Contributors:
 *   Erik Verhoeven - initial API and implementation
 ********************************************************************************/

#include "core.idl"

/**
 * @brief Software Defined Vehicle framework.
 */
module sdv
{
    /**
     * @brief Hardware specific features.
     */
    module hardware
    {
        /**
         * @brief Interface to obtain Hardware ID
         */
        interface IHardwareID
        {
            /**
            * @brief Gets the hardware ID of the current hardware.
            * It's same for the all processes running in the same hardware and different for the processes of each different hardwares.
            * @return Returns the hardware ID or 0 in case of failure.
            */
            uint64 GetHardwareID();
        };
    };
};
