 /********************************************************************************
 * Copyright (c) 2025-2026 ZF Friedrichshafen AG
 *
 * This program and the accompanying materials are made available under the 
 * terms of the Apache License Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-License-Identifier: Apache-2.0 
 ********************************************************************************/

/**
 * @brief Service to open the trunk
 * @details Service interface definition to open the trunk.
 */
interface ITrunkKitService
{
    /**
     * @brief Save call to open the trunk. Opening the trunk is onkly allowed when the vehicle is not moving
     * @return Returns whether the trunk could be opened or not.
     */
    boolean PopTrunk();
};