/**
@file signal_identifier.h
@date 2025-09-06 14:55:42
This file is the signal identifier header.
This file was generated by the DBC utility from:
  datalink_4doors_example.dbc
  DBC file version: 1.0.0.1
*/
#ifndef __DBC_GENERATED__SIGNALIDENTIFIER_H__20250906_145542_578__
#define __DBC_GENERATED__SIGNALIDENTIFIER_H__20250906_145542_578__

namespace Doors4ExampleFMU
{
   // Data Dispatch Service  signal names  to  dbc variable names                C-type   RX/TX  vss name space
    static std::string      dsDoor01LeftIsOpen  = "CAN_Input_L1.Door01LeftIsOpen";
    static std::string      dsDoor01RightIsOpen = "CAN_Input_R1.Door01RightIsOpen";
    static std::string      dsDoor02LeftIsOpen  = "CAN_Input_L2.Door02LeftIsOpen";
    static std::string      dsDoor02RightIsOpen = "CAN_Input_R2.Door02RightIsOpen";
    static std::string      dsLockDoor01Left    = "CAN_Output.LockDoor01Left";
    static std::string      dsLockDoor01Right   = "CAN_Output.LockDoor01Right";
    static std::string      dsLockDoor02Left    = "CAN_Output.LockDoor02Left";	
    static std::string      dsLockDoor02Right   = "CAN_Output.LockDoor02Right";
	
} // Doors4ExampleFMU

#endif // __DBC_GENERATED__SIGNALIDENTIFIER_H__20250906_145542_578__
