[Configuration]
Version = 100

[[Component]]
Path = "frontdoors_vd_frontdoorleft_rx.sdv"
Class = "Vehicle.Body.Door.Axle._01.Left_Device"

[[Component]]
Path = "frontdoors_bs_frontdoorleft_rx.sdv"
Class = "Vehicle.Body.Door.Axle._01.Left_Service"





