[Configuration]
Version = 100

[[Component]]
Path = "reardoors_vd_reardoorleft_rx.sdv"
Class = "Vehicle.Body.Door.Axle._02.Left_Device"

[[Component]]
Path = "reardoors_bs_reardoorleft_rx.sdv"
Class = "Vehicle.Body.Door.Axle._02.Left_Service"





