[Configuration]
Version = 100

[[Component]]
Path = "reardoors_vd_reardoorright_rx.sdv"
Class = "Vehicle.Body.Door.Axle._02.Right_Device"

[[Component]]
Path = "reardoors_bs_reardoorright_rx.sdv"
Class = "Vehicle.Body.Door.Axle._02.Right_Service"
